pyshop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("testy.urls")),
    path("users/", include("users.urls")),
    path("accounts/", include("allauth.urls")),
    path("bulls/", include("testy2.urls")),
]
# docker run -p 6379:6379 -d redis:5


#rm -f ./.git/index.lock
#cd .git
#del index.git
#del index.lock

testy/urls.py
from django.urls import path, re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url


urlpatterns = [
    path("", views.IndexView, name="index_page"),
    path("nature/", views.NatureCreate, name="nature_page"),  # nature=Nature
    path("nature/<int:pk>/", views.NatureDetail, name="nature_detail"),
    path("nature/hide/", views.HidePost, name="nature_hide"),
    path("comment/restrict/", views.CommentRestrict, name="comment_restrict"),
    path("post/<int:pk>/delete", views.NatureDelete.as_view(), name="nature_delete"),
    url(r"(?P<id>\d+)/nature/edit$", views.NatureEdit, name="nature_edit"),
    # for ajax
    # path("total_likes/", views.TotalLikes, name="total_likes"),
    path("nature/likes/", views.LikePost, name="like_post"),
    path("total_likes/<int:pk>/", views.TotalLikes, name="total_likes"),
    # it works for cmnt also.
    path("total_comments/<int:pk>/", views.TotalComments, name="total_comments"),
    path("nature/follow/", views.FollowUnfollow, name="follow_user"),
    path("nature/follower/request", views.AcceptFollower, name="accept_follower"),
    path("<str:username>/", views.ProfileView, name="profile_view"),
    re_path(r"^(?P<username>\w+)/followers$", views.FollowerList, name="followers"),
    re_path(r"^(?P<username>\w+)/following$", views.FollowerList, name="following"),
    path("search/", views.SearchUser, name="search_user"),
    path("notifications/", views.Notify, name="notify_page"),
    path("live/", views.LiveStream, name="live_page"),
    path("story/", views.StoryCreate, name="story_page"),
    path("story/<int:pk>/", views.StoryDetail, name="story_detail"),
    path("explore/", views.Explore, name="explore_page"),
    path("suggestion/", views.Suggestion, name="suggestion_page"),
    # archives
    path(
        "<int:user_id>/<int:year>/",
        views.NatureYearArchiveView.as_view(),
        name="nature_year_archive",
    ),
    path(
        "<int:user_id>/<int:year>/<int:month>/",
        views.NatureMonthArchiveView.as_view(month_format="%m"),
        name="archive_month_numeric",
    ),
    # Example: /2012/aug/
    path(
        "<int:user_id>/<int:year>/<str:month>/",
        views.NatureMonthArchiveView.as_view(),
        name="archive_month",
    ),
    path(
        "<int:user_id>/<int:year>/week/<int:week>/",
        views.NatureWeekArchiveView.as_view(),
        name="archive_week",
    ),
    path(
        "comment/<int:pk>/update", views.CommentUpdate.as_view(), name="comment_update"
    ),
    path(
        "comment/<int:pk>/delete", views.CommentDelete.as_view(), name="comment_delete"
    ),
    path("my/favourites/", views.FavouritePostList, name="fav_list"),
    path("favourites/edit/", views.FavouritePost, name="fav_edit"),
    path("test/123/", views.TestView, name="test_on"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

testy/models.py
from django.utils import timezone
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.shortcuts import reverse
from PIL import Image
from django.contrib.auth.models import AbstractBaseUser


class Nature(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="nature")
    caption = models.CharField(max_length=200, blank=True)
    pub_date = models.DateTimeField(default=timezone.now)
    location = models.CharField(max_length=19, blank=True)
    likes = models.ManyToManyField(User, related_name="likes", blank=True)
    # is_photo = models.BooleanField(default=False, blank=True)
    hide_post = models.BooleanField(default=False, blank=True)
    restrict_comment = models.BooleanField(default=False, blank=True)
    favourite = models.ManyToManyField(User, related_name="favourite", blank=True)

    class Meta:
        ordering = ["-pub_date"]

    def __str__(self):
        return f"{self.user.username} nature"

    def total_likes(self):
        return self.likes.count()

    def get_absolute_url(self):
        return reverse("nature_detail", args=[str(self.id)])

    def one_day(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def is_latest(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=2)

    def was_recent(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(seconds=30)


class NatureImage(models.Model):
    nature = models.ForeignKey(Nature, on_delete=models.CASCADE, related_name="media")
    about = models.CharField(max_length=50, blank=True)
    photo = models.FileField(upload_to="images/", blank=True, null=True)
    is_photo = models.BooleanField(default=False, blank=True)

    """
    def save(self, *args, **kwargs):

        super().save(*args, **kwargs)
        if not self.photo:
            return

        image = Image.open(self.photo.path)
        # change filename

        if image.height > 1200 or image.width > 1200:
            output_size = (1000, 1000)
            image.thumbnail(output_size)
            image.save(self.photo.path)
            print("image resized from model")
    """
    def __str__(self):
        return f"{self.nature.user.username} images"


class Comments(models.Model):
    nature = models.ForeignKey(Nature, on_delete=models.CASCADE, default=None)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # likes = models.ManyToManyField(User, related_name="c_likes", blank=True)
    reply = models.ForeignKey(
        "self", related_name="replies", on_delete=models.CASCADE, null=True
    )
    comment = models.TextField(max_length=50)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["timestamp"]

    def was_recent(self):
        return self.timestamp >= timezone.now() - datetime.timedelta(seconds=30)

    def __str__(self):
        return self.comment


class Contact(models.Model):
    user_from = models.ForeignKey(User, related_name="u_from", on_delete=models.CASCADE)
    user_to = models.ForeignKey(User, related_name="u_to", on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["user_from", "user_to"], name="unique users"
            )
        ]

        ordering = ["-created"]

    def __str__(self):
        return "{} follows {}".format(self.user_from, self.user_to)

    def was_recent(self):
        return self.created >= timezone.now() - datetime.timedelta(days=1)

    """ 
    def clean(self):
        if self.user_to.profile.is_private:
            return
    """


User.add_to_class(
    "following",
    models.ManyToManyField(
        "self", through=Contact, related_name="followers", symmetrical=False
    ),
)


class Notification(models.Model):
    user = models.ForeignKey(
        User, related_name="notes", on_delete=models.CASCADE, default=None
    )
    user_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    # this should be removed "default=none" while lauch caz no objects
    content = models.CharField(max_length=100)
    link = models.PositiveIntegerField(blank=True, default=0)
    is_like = models.BooleanField(blank=True, default=False)
    is_comment = models.BooleanField(blank=True, default=False)
    is_follow = models.BooleanField(blank=True, default=False)
    is_follow_request = models.BooleanField(blank=True, default=False)
    created = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ["-created"]

    def __str__(self):
        return self.content


# featured posts
class Story(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="story")
    photo = models.FileField(upload_to="images/", blank=True)
    is_photo = models.BooleanField(default=False, blank=True)
    pub_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-pub_date"]
    """ 
    def save(self, *args, **kwargs):
        if not self.photo:
            return
        image = Image.open(self.photo.path)
        if image.height > 600 or image.width > 600:
            output_size = (500, 500)
            image.thumbnail(output_size)
            image.save(self.photo.path)
            print("image resized from model")

        super(Nature, self).save(*args, **kwargs) 
    """

    def __str__(self):
        return f"{self.user.username} story"

    def is_story(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def get_absolute_url(self):
        return reverse("story_detail", args=[str(self.id)])


""" 
class Live(models.model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="live")
    photo = models.FileField(upload_to="images/", blank=True)
    pub_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-pub_date"]

    def __str__(self):
        return f"{self.user.username} live video"
"""


class Test(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="live")
    photo = models.ImageField(upload_to="images/", blank=True)
    pub_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-pub_date"]

    def __str__(self):
        return f"{self.user.username} test photo/video"

testy/forms.py
from django import forms
from .models import (
    Nature,
    Comments,
    Story,
    Test,
)
from users.models import Profile
from django.contrib.auth.models import User


class NatureForm(forms.ModelForm):
    class Meta:
        model = Nature
        fields = [
            "caption",
        ]

        labels = {
            "caption": "Add Caption",
        }


class NatureEditForm(forms.ModelForm):
    class Meta:
        model = Nature
        fields = [
            "caption",
            "hide_post",
            "restrict_comment",
        ]


class TestForm(forms.ModelForm):
    class Meta:
        model = Test
        fields = [
            "photo",
        ]

        labels = {
            "photo": "Photo/Video",
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ["comment"]

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"

        self.fields["comment"].widget.attrs["rows"] = 1
        # self.fields["comment"].widget.attrs["columns"] = 15


class CommentEditForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = [
            "comment",
        ]


class StoryForm(forms.ModelForm):
    class Meta:
        model = Story
        fields = [
            "photo",
        ]

        labels = {
            "photo": "add your story",
        }

testy/templates/testy/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Testy{% endblock title %}</title>
    {% load static %}
    <link
      rel="shortcut icon"
      href="https://salilesh-bucket.s3.us-east-2.amazonaws.com/title_logo.ico"
    />
    {% comment %} <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'testy/css/base.css' %}"
    /> {% endcomment %}
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
      integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ"
      crossorigin="anonymous"
    />
    <style>
      {% block otherCSS %}
      {% comment %} css goes here! {% endcomment %}
      {% endblock otherCSS %}
    </style>
  </head>

  <body>
    {% include 'testy/navbar.html' %}

    <div class="container">
      <div class="row">
        <div class="col-sm-2 float-left">
          {% block left_side %} {% endblock left_side %}
        </div>
        <div class="col-sm-8">
          <h6 class="border-bottom border-gray pb-2 mb-0">
            {% block intro_index %}Recent updates{% endblock %}
          </h6>
          {% block content %} {% endblock content %}
        </div>
        
        <div class="col-sm-2 float-right">
          {% block right_side %}
          
          {% endblock right_side %}
        </div>
      </div>
    </div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript">
          $(document).ready(function (event) {
            $('#delete').click(function () {
              return confirm("Are you sure to delete this post?");
            });

          $(document).on('click', '#like', function (event) {
            event.preventDefault();
            var pk = $(this).attr('value');
            var likeSection="like-section"+pk;
            $.ajax({
              type: 'POST',
              url: '{% url "like_post" %}',
              data: { 'id': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}' },
              dataType: 'json',
              success: function (response) {
                $('#'+likeSection).html(response['form'])
                console.log($('#'+likeSection).html(response['form']));
              },
              error: function (rs, e) {
                console.log(rs.responseText);
              },
            });
          });
            {% comment %}

          $(document).on('click', '#all-likes', function (event) {
              event.preventDefault();
              var pk = $(this).attr('value');
              $.ajax({
                type: 'POST',
                url: '{% url "total_likes" %}',
                data: { 'id': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}' },
                dataType: 'json',
                success: function (response) {
                  $('#total-likes').html(response['form']);

                },
                error: function (rs, e) {
                  console.log(rs.responseText);
                },
              });
            });
      {% endcomment %}

            $(document).on('click', '#follow', function (event) {
              event.preventDefault();
              var pk = $(this).attr('value');
              var ajaxLoading=$("#icon"+pk);
              $(this).html(ajaxLoading).show();
              var followSection="follow-section"+pk
              $.ajax({
                type: 'POST',
                url: '{% url "follow_user" %}',
                data: { 'id': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}' },
                dataType: 'json',
                success: function (response) {
                  $('#'+ajaxLoading).hide();
                  $('.'+followSection).html(response['form']);

                },
                error: function (rs, e) {
                  console.log(rs.responseText);
                },
              });
            });

            $(document).on('click', '#follow-form', function (event) {
              event.preventDefault();
              var pk = $(this).attr('value');
              $(this).attr('class', 'btn btn-light');
              $(this).html("<img src='https://salilesh-bucket.s3.us-east-2.amazonaws.com/ajax-loader.gif' alt='Loading'>");
              console.log($(this).html());
              var followSection="follow-section"+pk;

              $.ajax({
                type: 'POST',
                url: '{% url "follow_user" %}',
                data: { 'id': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}','just_form':pk,},
                dataType: 'json',
                success: function (response) {
                  $('.'+followSection).html(response['form']);
                },
                error: function (rs, e) {
                  console.log(rs.responseText);
                },
              });
            });


            $(document).on('click', '#favourite', function (event) {
              event.preventDefault();
              var pk = $(this).attr('value');
              var favSection="fav-section"+pk
              $.ajax({
                type: 'POST',
                url: '{% url "fav_edit" %}',
                data: { 'id': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}' },
                dataType: 'json',
                success: function (response) {
                  $('#'+favSection).html(response['form'])
                  console.log($('#'+favSection).html(response['form']));
                },
                error: function (rs, e) {
                  console.log(rs.responseText);
                },
              });
            });



          {% block otherJs %}

          {% endblock otherJs %}


          });
          {% block plainJS %}

          {% endblock plainJS %}
    </script>
    <!--  <script src="{% static 'testy/js/profile_view.js' %}"></script>
  <script src="{% static 'testy/js/slides.js' %}"></script> -->
  </body>
</html>

testy/templates/testy/comment_restrict.html
<div id="restrictAllow{{ nature.id }}">
<form action="." method="POST">
    {% csrf_token %}
    {% if nature.restrict_comment == True %}
    <button type="submit" class="dropdown-item" id="restrict-allow" name="tweet_id" value="{{ nature.id }}">Allow comment</button>
    {% elif nature.restrict_comment == False %}
    <button type="submit" class="dropdown-item" id="restrict-allow" name="tweet_id" value="{{ nature.id }}">Restrict comment</button>
    {% endif %}
</form>
</div>

testy/templates/testy/comments.html
{% load humanize %}
<a href="{% url 'total_comments' nature.id %}" name="comments">
  <p><span class="badge">{{ nature.comments_set.count }} </span> Comment{{ comments|pluralize }}</p>
</a>

<div class="main-comment-section">
{% include 'testy/comment_form.html' %}
{% for comment in comments %}
<div class="media">
  <a class="mr-3" href="{% url 'profile_view' comment.user.username %}">
    <img src="{{ comment.user.profile.image.url }}" style="height:40px ;width:40px;" class="rounded-circle mr-3"
      alt="img.">
    <div class="media-body">
      <b>
        <h5 class="mt-0 mb-1">@{{ comment.user.username }} </h5>
      </b>
  </a>

  <div id="updated-comment-section{{ comment.id }}">
    {% include 'testy/update.html' %}
  </div>

  <p>{{ comment.comment }}</p>

  {% include "testy/cmnt_reply_form.html" %}


<div style="display:none;" id="toggle-replies{{ comment.id }}">
  {% for reply in comment.replies.all %}
  <div class="media mt-3">
    <a class="mr-3" href="{% url 'profile_view' reply.user.username %}">
      <img src="{{ reply.user.profile.image.url }}" style="height:40px; width:40px;" class="rounded-circle mr-3"
        alt="img">
      <div class="media-body">
        <b>
          <h5 class="mt-0 mb-1">@{{ reply.user.username }}</h5>
        </b>
    </a>

    <div id="updated-comment-section{{ reply.id }}">
      {% include 'testy/update.html' %}
    </div>

    <p>
      {{ reply.comment }}
    </p>

    {% include "testy/cmnt_reply_form.html" %}

  </div><!-- media body for reply -->

</div>
{% endfor %}
</div>


</div><!-- media body ends here -->
</div>
<hr>
{% endfor%}

</div>

testy/templates/testy/comments_delete_form.html
{% extends 'testy/base.html' %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    {% if request.user.is_authenticated %}
    <input type="submit" value="Edit" class="btn btn-primary float-right reply-btn">
    {% else %}
    <input type="submit" value="Edit" class="btn btn-primary reply-btn float-right" disabled>
    {% endif %}
</form>
{% endblock content %}

testy/templates/testy/explore.html
{% extends 'testy/base.html' %}
{% block content %}
{% for nature in explores %}

<h6>
    <a href="{% url 'profile_view' userid=nature.user.id %}">
        <img class="rounded-circle" width="30" height="30" src="{{ nature.user.profile.image.url }}" alt="i">
        <strong>@{{ nature.user.username }}</strong>
    </a>
</h6>
<a href="{% url 'nature_detail' nature.id %}">
{% include 'testy/carousel.html' %}
</a>
<br>
{% endfor %}

{% endblock content %}

testy/templates/testy/fav_natures.html
{% extends 'testy/base.html' %}
{% load humanize %}
{% block content %}
{% if messages %}
<div {% if message.tags %} class="{{ message.tags }}" {% endif %}>
    {% for message in messages %}
    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important:
    {% endif %}

    {% endfor %}
</div>
{% endif %}

{% for nature in favourite_posts %}
<h6>
    <a href="{% url 'profile_view' nature.user.username %}">
        <img class="rounded-circle" width="30" height="30" src="{{ nature.user.profile.image.url }}" alt="i">
        <strong>@{{ nature.user.username }}</strong>
    </a>
</h6>
<a href="{% url 'nature_detail' nature.id %}">
{% include "testy/carousel.html" %}
</a>
<br>

<div id="fav-section{{ nature.id }}">
{% include 'testy/fav_section.html' %}
</div>

<br><hr>
{% empty %}
<h3>You haven't added any post to favourite lists.<h3>
{% endfor %}


{% endblock content %}

testy/templates/testy/like_comment.html
<div class="d-flex flex-row justify-content-around">
  <div class="p-2" id="like-section{{ nature.id }}">
    {% include 'testy/like_section.html' %}
  </div>
  
  <div class="p-2">
    <a href="{% url 'nature_detail' nature.id %}">
      <button class="btn btn-info"><span class="fa fa-comment"></span></button>
    </a>
  </div>
  <div class="p-2" id="fav-section{{ nature.id }}">
    {% include 'testy/fav_section.html' %}
  </div>
</div>

testy/templates/testy/nature.html
{% extends 'testy/base.html'%}
{% block content %}
  {% if error_message %}
  <p><strong>{{ error_message }}</strong></p>
  {% endif %}
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Tweet" class="btn btn-primary btn-block"/>
  </form>
{% endblock content %}

testy/templates/testy/nature_archive_year.html
<ul>
    {% for date in date_list %}
        <li>{{ date|date }}</li>
    {% endfor %}
</ul>

<div>
    <h1>All Articles for {{ year|date:"Y" }}</h1>
    {% for obj in object_list %}
        <p>
        <h6>{{ obj.user.username }}</h6>
        {% for o in obj.media.all %}
            <h4>{{ o.about }}</h4>,
        {% endfor %}
        - {{ obj.pub_date|date:"F j, Y" }}
        </p>
    {% endfor %}
</div>

testy/templates/testy/nature_hide.html
<div id="hide-show{{ nature.id }}">
<form action="." method="POST">
    {% csrf_token %}
    {% if nature.hide_post == False or is_hidden is False %}
    <button type="submit" class="dropdown-item" id="hide" name="tweet_id" value="{{ nature.id }}">Hide post</button>
    {% elif nature.hide_post or is_hidden %}
    <button type="submit" class="dropdown-item" id="hide" name="tweet_id" value="{{ nature.id }}">Show post</button>
    {% endif %}
</form>
</div>

testy/templates/testy/navbar.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="{% url 'index_page' %}">
    <img
      src="https://salilesh-bucket.s3.us-east-2.amazonaws.com/index_logo.gif"
      width="30"
      height="30"
      alt=""
    />
  </a>
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarCollapse"
    aria-controls="navbarCollapse"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    {% if request.user.is_authenticated %}

    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'index_page' %}"
          >Home <span class="sr-only">(current)</span></a
        >
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'notify_page' %}"
          >Notifications
          <span id="notify-span" class="badge badge-pill align-text-center"
            >{{ request.user.notes.count }}</span
          >
        </a>
      </li>
      <li class="nav-item">
        {% if request.user.is_authenticated %}
        <a
          class="nav-link"
          href="{% url 'profile_view' request.user.username %}"
          >Profile</a
        >
        {% endif %}
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'fav_list' %}">Favourites</a>
      </li>

      <li class="nav-item dropdown">
        <a
          class="nav-link dropdown-toggle"
          href="#"
          id="dropdown01"
          data-toggle="dropdown"
          aria-haspopup="true"
          aria-expanded="false"
          >Settings</a
        >
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="{% url 'account_setting' %}"
            >Account Settings</a
          >

          <a class="dropdown-item" href="{% url 'logout' %}">Switch Account</a>
          <a class="dropdown-item" href="{% url 'logout' %}"
            >Logout <b>@{{ request.user.username}}</b></a
          >
        </div>
      </li>
    </ul>
    {% else %} {% endif %} {% if request.user.is_authenticated %}
    <form
      class="input-group mb-3"
      style="max-width: 300px"
      method="GET"
      action="{% url 'search_user' %}"
    >
      <input
        class="form-control"
        type="text"
        id="search"
        aria-label="Search"
        placeholder="Search Testy"
        name="q"
      />
      <div class="input-group-append">
        <button class="btn btn-success" id="search-user" type="submit">
          Go
        </button>
      </div>
    </form>
    {% endif %}
  </div>
</nav>
<div class="nav-scroller bg-white shadow-sm" style="margin-top: 5rem">
  <nav class="nav nav-underline">
    {% if request.user.is_authenticated %}
    <a class="nav-link" href="{% url 'explore_page' %}">Explore</a>
    <a class="nav-link" href="{% url 'suggestion_page' %}">Suggestions</a>
    <a class="nav-link" href="{% url 'story_page' %}" %>Story</a>
    <a class="nav-link" href="{% url 'live_page' %}">Go Live</a>
    <a class="nav-link" href="{% url 'nature_page' %}">Tweet</a>
    {% else %}
    <h4 style="margin-left: 6rem">Welcome to Testy</h4>
    <a href="{% url 'login' %}" class="btn btn-primary">Login</a>
    {% endif %}
  </nav>
</div>

testy/templates/testy/update.html
<div class="btn-group dropleft float-right">
 
    <i class="fa fa-caret-left fa-3x dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" aria-hidden="true"></i>
  
  <div class="dropdown-menu">
  {% if comment.user == request.user or reply.user == request.user %}
  {% if comment %}
  <a href="{% url 'comment_update' comment.id %}" type="button" class="dropdown-item">
  Edit comment
  {% elif reply %}
  <a href="{% url 'comment_update' reply.id %}" type="button" class="dropdown-item">
  Edit reply
  {% endif %}
</a>

    
    <a class="dropdown-item" href="{% url 'comment_delete' comment.id %}">Delete comment</a>
    {% endif %}

    {% if not comment.user  == request.user or reply.user == request.user %}
    <a class="dropdown-item" href="#">Report comment</a>
    {% endif %}
  </div>
</div>
{% comment %} for cmnt {% endcomment %}